Document: piccolo3-utils
Title: Debian piccolo3-utils Manual
Author: <insert document author here>
Abstract: This manual describes what piccolo3-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piccolo3-utils/piccolo3-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/piccolo3-utils/piccolo3-utils.ps.gz

Format: text
Files: /usr/share/doc/piccolo3-utils/piccolo3-utils.text.gz

Format: HTML
Index: /usr/share/doc/piccolo3-utils/html/index.html
Files: /usr/share/doc/piccolo3-utils/html/*.html
